addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"        % "0.2.2")
addSbtPlugin("io.spray"                  % "sbt-revolver"        % "0.9.1")
addSbtPlugin("com.timushev.sbt"          % "sbt-rewarn"          % "0.1.3")
addSbtPlugin("com.typesafe.sbt"          % "sbt-native-packager" % "1.7.6")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"        % "2.5.0")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"        % "0.10.4")
